---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-21T11:42:15Z"
  name: carts-primary
  resourceVersion: "932205"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: f7208ef1-0c53-11ea-a59b-42010a840122
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
